[tools]
go = "1.26.2"
helm = "4.1.4"
kubectl = "latest"
kind = "latest"
kustomize = "5.8.1"
golangci-lint = "2.12.2"
kube-controller-tools = "0.21.0"
setup-envtest = "0.24.0"
operator-sdk = "1.42.2"
"aqua:operator-framework/operator-registry" = "1.67.0"
