---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate-upgrade-home-operations-com-v1alpha1-kubernetes
    failurePolicy: Fail
    name: vkubernetes.kb.io
    rules:
      - apiGroups:
          - upgrade.home-operations.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - kuberneteses
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate-upgrade-home-operations-com-v1alpha1-talosplan
    failurePolicy: Fail
    name: vtalosplan.kb.io
    rules:
      - apiGroups:
          - upgrade.home-operations.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - talosplans
    sideEffects: None
