---
# This rule is not used by the project talup itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to upgrade.home-operations.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: talup
    app.kubernetes.io/managed-by: kustomize
  name: kubernetes-viewer-role
rules:
  - apiGroups:
      - upgrade.home-operations.com
    resources:
      - kubernetes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - upgrade.home-operations.com
    resources:
      - kubernetes/status
    verbs:
      - get
