---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - upgrade.home-operations.com
  resources:
  - kubernetes
  - talosupgrades
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - upgrade.home-operations.com
  resources:
  - kubernetes/finalizers
  - talosupgrades/finalizers
  verbs:
  - update
- apiGroups:
  - upgrade.home-operations.com
  resources:
  - kubernetes/status
  - talosupgrades/status
  verbs:
  - get
  - patch
  - update
