---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - talup.home-operations.com
    resources:
      - talosupgrades
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - talup.home-operations.com
    resources:
      - talosupgrades/finalizers
    verbs:
      - update
  - apiGroups:
      - talup.home-operations.com
    resources:
      - talosupgrades/status
    verbs:
      - get
      - patch
      - update
