---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  release:
    name: Release
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: docker/github-builder/.github/workflows/build.yml@17bd7d64200cae4ba58ffc099934e8012ae320f2 # v1.10.0
    with:
      build-args: |
        VERSION=${{ github.ref_name }}
        REVISION=${{ github.sha }}
      cache: true
      meta-images: ghcr.io/${{ github.repository }}
      meta-tags: |
        type=semver,pattern={{version}}
        type=raw,value=rolling,enable=${{ github.event_name == 'release' }}
        type=ref,event=branch
      output: image
      platforms: linux/amd64,linux/arm64
      push: true
      sbom: true
      sign: true
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  helm:
    name: Helm
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    env:
      VERSION: ${{ github.event.release.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          cache: false
          experimental: true
          install_args: --locked

      - name: Generate manifests and CRDs
        run: mise run helm-crds

      - name: Package Helm chart
        run: |
          helm package charts/tuppr \
            --version "${VERSION}" \
            --app-version "${VERSION}"

      - name: Log in to Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Helm chart to GHCR
        run: |-
          helm push "tuppr-${VERSION}.tgz" "oci://ghcr.io/${{ github.repository_owner }}/charts"
