---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".release-please-manifest.json"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".release-please-manifest.json"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

env:
  # renovate: datasource=github-releases depName=helm-unittest/helm-unittest
  HELM_UNITTEST_VERSION: "v1.1.2"

jobs:
  test:
    name: Go Tests
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Mise
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
        with:
          experimental: true
          install_args: --locked

      - name: Cache Go modules and build
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Check go.mod tidiness
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: Running Unit Tests
        run: mise run test

      - name: Running Integration Tests
        run: mise run test-integration

  helm-test:
    name: Helm Unit Tests
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Mise and required tools
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
        with:
          experimental: true
          install_args: --locked

      - name: Run helm unit tests
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest --version "${HELM_UNITTEST_VERSION}" --verify=false
          mise run helm-test

      - name: Check chart docs are current
        run: mise run helm-docs-check
